/* Luxury Guest V2 — editorial content and licensed mood photography.
   Photos illustrate a universe; they do not assert ownership or live availability. */
window.LG = {
  phone: '+33 7 68 27 57 69', tel: '+33768275769', whatsapp: '33768275769', email: 'luxuryguest75@gmail.com',
  images: {
    hero: ['1506059612708-99d6c258160e', 'Piscine et palmiers au crépuscule', 'Jörg Angeli', '1tyuLfDOnG0'],
    villa: ['1540882082344-a56ecd70ba96', 'Villa éclairée et piscine à la tombée du jour', 'Alan J. Hendry', 'zVf-R-r3szw'],
    suite: ['1611892440504-42a792e24d32', 'Suite élégante aux matières et lumières douces', 'visualsofdana', 'T5pL6ciEn-I'],
    chambre: ['1618773928121-c32242e63f39', 'Chambre haut de gamme, literie et éclairage soignés', 'Vojtech Bruzek', 'Yrxr3bsPdS0'],
    spa: ['1526498840002-87400e890f76', 'Bassin illuminé dans un décor architectural raffiné', 'Pedro Sostre', 'MQIbeeXmzLc'],
    voiture: ['1687634366004-6cf64578ee81', 'Véhicule de prestige noir', 'Franco Debartolo', 'MD_7QNWJick'],
    yacht: ['1569263979104-865ab7cd8d13', 'Yacht de plaisance sur l’eau', 'Viktor Ritsvall', 'FWJinfDsIn8'],
    restaurant: ['1621873495868-6c5774cf6012', 'Une atmosphère de restaurant haut de gamme', 'Pylyp Sukhenko', 'xyIEfcjM3ew'],
    paris: ['1502602898657-3e91760cbb34', 'La tour Eiffel et Paris', 'Unsplash', ''],
    'cote-azur': ['1503696967350-ad1874122058', 'Littoral niçois sur la Côte d’Azur', 'John Jason', 'mpVZVCClgac'],
    courchevel: ['1649421811395-5bfcf16cc37a', 'Paysage alpin dans la région de Courchevel', 'Piotr Figlarz', 'lDoujbHM3Qk'],
    marrakech: ['1597212618440-806262de4f6b', 'Architecture et atmosphère de Marrakech', 'Paul Macallan', 'CFKksjYRSQ8'],
    dubai: ['1512453979798-5ea266f8880c', 'Architecture et skyline de Dubaï', 'Unsplash', '']
  },
  services: [
    {id:'loveroom',name:'Loveroom',icon:'heart',image:'suite',eyebrow:'Une parenthèse à deux',title:'L’intimité.<br>Tout simplement.',desc:'Échappez-vous le temps d’une nuit dans un espace romantique et intimiste.',intro:'Une occasion à célébrer, une surprise à organiser, ou simplement l’envie de se retrouver. Nous recherchons le cadre qui correspond à votre moment, en toute discrétion.',detail:'Dites-nous vos dates, votre destination et l’ambiance souhaitée. La conciergerie vous propose les possibilités adaptées, avec les équipements et les conditions précisés avant toute confirmation.',highlights:['Cadre intimiste','Élégance et confort','Attention personnalisée'],offers:[['suite','Une nuit à deux','Une chambre ou une suite choisie selon votre envie d’évasion et votre budget.'],['spa','Une pause bien-être','Bain à remous, spa ou espace détente : indiquez les équipements que vous souhaitez.'],['chambre','Une occasion particulière','Anniversaire, surprise ou escapade romantique : partagez les détails de votre projet.']],note:'Les équipements, décorations et attentions varient selon les lieux. Ils sont confirmés dans la proposition personnalisée.'},
    {id:'logements',name:'Logements',icon:'home',image:'villa',eyebrow:'Votre adresse, autrement',title:'Des lieux à vivre.<br>Des séjours à part.',desc:'Villas de luxe et appartements d’exception pour vos séjours.',intro:'De l’appartement en ville à la villa avec piscine, nous partons de votre façon de voyager. Intimité, emplacement, espace : votre prochaine adresse se choisit dans les détails.',detail:'Un séjour à deux, en famille ou entre amis. Précisez votre destination, le nombre de voyageurs et vos attentes ; nous étudions une sélection adaptée aux disponibilités.',highlights:['Villas & appartements','Accueil personnalisé','Sélection sur demande'],offers:[['villa','Villas de prestige','De l’espace, un cadre privilégié et les équipements adaptés à votre séjour.'],['suite','Appartements d’exception','Une adresse confortable pour profiter de la ville à votre rythme.'],['hero','Un séjour sur mesure','Logement, transferts et réservations : réunissez vos demandes auprès de la conciergerie.']],note:'Ces photographies sont des inspirations, pas des annonces de biens disponibles. Les photos du logement proposé, ses équipements et son tarif sont transmis avant confirmation.'},
    {id:'transport',name:'Transport',icon:'car',image:'voiture',eyebrow:'L’élégance en mouvement',title:'Chaque trajet<br>fait partie du séjour.',desc:'Chauffeur privé, véhicules de prestige et transferts personnalisés.',intro:'Un transfert, une mise à disposition ou un déplacement particulier. Luxury Guest vous accompagne dans l’organisation de votre transport, selon votre itinéraire et vos horaires.',detail:'Partagez le lieu de départ, la destination, la date, l’heure et le nombre de passagers. Nous vous orientons vers une proposition adaptée à votre déplacement.',highlights:['Chauffeur privé','Mise à disposition','Transferts sur demande'],offers:[['voiture','Chauffeur privé','Pour un transfert ou une mise à disposition, avec un itinéraire organisé selon vos besoins.'],['voiture','Location de prestige','Une demande de véhicule haut de gamme, étudiée selon les modèles et conditions disponibles.'],['dubai','Transfert exclusif','Une demande de jet privé ou d’avion, avec une proposition spécifique à votre trajet.']],note:'Le véhicule photographié illustre l’univers du service. Modèle, capacité, opérateur, disponibilité et prix sont à confirmer pour chaque demande.'},
    {id:'activites',name:'Activités VIP',icon:'compass',image:'yacht',eyebrow:'Des souvenirs, pas un programme',title:'Vivre plus.<br>Prévoir moins.',desc:'Yacht, expériences aériennes et excursions pour des moments à part.',intro:'Une journée sur l’eau, un panorama depuis les airs ou une escapade dans le désert. Partagez votre idée ; nous vous aidons à lui donner une forme.',detail:'Nous adaptons la recherche à votre destination, à la composition de votre groupe et au temps dont vous disposez. Les possibilités dépendent des prestataires, des disponibilités et des conditions locales.',highlights:['Journée en yacht','Hélicoptère / montgolfière','Excursions personnalisées'],offers:[['yacht','Une journée en yacht','Une sortie en mer à organiser selon le nombre de participants et le programme souhaité.'],['dubai','Prendre de la hauteur','Hélicoptère ou montgolfière : une autre perspective sur votre destination.'],['marrakech','Une escapade dans le désert','Une expérience à construire selon vos envies et les possibilités sur place.']],note:'Les activités sont proposées sur demande. Les conditions météorologiques, les contraintes de sécurité et les règles des opérateurs peuvent modifier le programme.'},
    {id:'reservations-vip',name:'Réservations VIP',icon:'star',image:'restaurant',eyebrow:'L’art de bien recevoir',title:'La bonne table.<br>Le bon moment.',desc:'Restaurants, sorties et tables privilégiées selon vos envies.',intro:'Un dîner en tête-à-tête, une table pour votre groupe ou une soirée particulière. Indiquez-nous l’ambiance recherchée et nous étudions votre demande.',detail:'Destination, date, nombre de personnes, établissement souhaité et préférences : chaque information nous aide à affiner la recherche. Une demande n’est jamais une garantie d’accès.',highlights:['Restaurants','Night-clubs','Tables sur demande'],offers:[['restaurant','Une table pour vous','Un dîner à organiser en fonction de vos préférences et des disponibilités des établissements.'],['paris','Une soirée à part','Partagez le lieu, la date et le nombre de participants pour préparer votre sortie.'],['restaurant','Un moment à célébrer','Une occasion particulière et les attentions souhaitées, à préciser avec la conciergerie.']],note:'Toute réservation ou admission reste soumise à la disponibilité, à l’acceptation et aux conditions de l’établissement concerné.'}
  ],
  destinations: [
    {id:'paris',name:'Paris',region:'France',kicker:'L’élégance parisienne',title:'Paris.<br>À votre rythme.',intro:'Une escapade en ville, un dîner ou un séjour à organiser. Retrouvez l’univers Luxury Guest à Paris, avec des demandes pensées autour de vos envies.',services:['logements','transport','reservations-vip'],inspiration:'Un appartement pour le séjour, un transfert à votre arrivée et une table pour la soirée : réunissez votre projet dans une seule demande.'},
    {id:'cote-azur',name:'Côte d’Azur',region:'France',kicker:'L’esprit Riviera',title:'La Riviera.<br>En toute liberté.',intro:'Une villa, une sortie en mer ou une soirée sur la côte. Composez votre séjour sur la Côte d’Azur avec un accompagnement personnalisé.',services:['logements','activites','transport'],inspiration:'Partagez votre point de chute sur la côte, vos dates et le rythme de votre séjour. La sélection dépend des disponibilités locales.'},
    {id:'courchevel',name:'Courchevel',region:'France',kicker:'Une échappée en altitude',title:'Courchevel.<br>Une autre altitude.',intro:'Un séjour à la montagne avec un logement adapté, des transferts organisés et vos réservations préparées selon vos demandes.',services:['logements','transport','reservations-vip'],inspiration:'Précisez le nombre de voyageurs, la période et vos attentes en matière d’emplacement, d’équipements et de déplacements.'},
    {id:'marrakech',name:'Marrakech',region:'International',kicker:'La chaleur d’une escapade',title:'Marrakech.<br>Laissez-vous porter.',intro:'Une villa pour se retrouver, une table pour la soirée ou une excursion : préparez votre parenthèse à Marrakech avec Luxury Guest.',services:['logements','activites','reservations-vip'],inspiration:'Du séjour à l’expérience, indiquez les moments que vous souhaitez organiser. Nous étudions les possibilités selon votre programme.'},
    {id:'dubai',name:'Dubaï',region:'International',kicker:'Des perspectives nouvelles',title:'Dubaï.<br>Voir plus grand.',intro:'Un appartement, un véhicule de prestige ou une journée en yacht. Construisez votre programme à Dubaï à partir de vos envies.',services:['logements','transport','activites'],inspiration:'Transmettez vos dates, votre destination d’arrivée et les prestations souhaitées pour préparer une proposition cohérente.'}
  ],
  faqs: [
    ['Comment faire une demande ?', 'Choisissez un service et une destination, puis complétez le formulaire. Un récapitulatif est préparé ; vous pouvez ensuite le transmettre à Luxury Guest via WhatsApp ou votre messagerie e-mail.'],
    ['Le formulaire confirme-t-il une réservation ?', 'Non. Il prépare une demande à transmettre à la conciergerie. La disponibilité, le prix et les conditions doivent être validés avant toute confirmation. Aucun paiement n’est prélevé sur ce site.'],
    ['Puis-je demander plusieurs prestations ?', 'Oui. Choisissez « Plusieurs services / sur mesure » dans le formulaire et précisez les prestations souhaitées : logement, chauffeur, activités ou réservations.'],
    ['Dans quelles destinations intervenez-vous ?', 'Les destinations présentées sont Paris, la Côte d’Azur, Courchevel, Marrakech et Dubaï. Pour un autre lieu, sélectionnez « Autre destination » ; votre demande sera étudiée.'],
    ['Les photographies montrent-elles les biens réservables ?', 'Les photographies du site illustrent l’univers de Luxury Guest. Elles ne constituent pas un catalogue de disponibilités. Les informations du bien ou de la prestation proposés sont précisées avant confirmation.'],
    ['Comment les tarifs sont-ils définis ?', 'Chaque demande fait l’objet d’une proposition selon la prestation, les dates, la destination et les disponibilités. Vous pouvez indiquer un budget indicatif pour guider la recherche.'],
    ['Comment modifier ou annuler une prestation ?', 'Contactez directement la conciergerie. Les possibilités de modification et d’annulation dépendent des conditions de la prestation, qui vous sont communiquées avant confirmation.'],
    ['Comment vous joindre directement ?', 'Par téléphone ou WhatsApp au +33 7 68 27 57 69, ou par e-mail à luxuryguest75@gmail.com.']
  ]
};
